//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_Banreservas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Persona
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Debe ingresar un nombre")]
        [MaxLength(100, ErrorMessage = "El campo no puede tener más de 100 caracteres")]
        [RegularExpression("^[A-Za-z0-9_-]*$", ErrorMessage = "El nombre no puede contener caracteres especiales")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Debe ingresar una fecha válida")]
        [DisplayName("Fecha de nacimiento")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime FechaDeNacimiento { get; set; }
    }
}
